### PR TITLE
Design

### PR DESCRIPTION
**Pull request by eggzilla**
Added prototype implementation for plain style. Should enable compilation without ufcd. Please test!

### CODE REVIEW

**Comment by eggzilla** [comment]
I forgot to mention that the changes have not affected compiling with ufcd for me.
The main changes for each lecture can be found in the directory:
Styles/Lecture/plain
There is still some colors definded there (Mittel-Blau), where we should decided what to do.

Moreover I had to replace \ufcdSetup{mainlanguage=english} in the LectureSettings_eng.tex
with \usepackage[english]{babel}

I had some trouble to get Lecture 10 compiling and had to remove removed \usepackage{paralist} from Lecture-10/Packages/LecturePackages_General.tex, it seems to be incompatible with beamer.

Multiple changes to \begin{frame}{Binary Search Trees}{Implementation - Lookup} slide
%\begin{itemize}[{\color{black!50!white}\footnotesize$\blacksquare$}] in 030_SearchTrees.tex

**Comment by eggzilla** [comment]
Ok, I just saw that simply replacing  \ufcdSetup{mainlanguage=english} seems to affect figure labels, i will put this in a conditional statement

**Comment by michauhl** [comment]
It's working!

**Comment by TobiasFaller** [comment]
I added an automated build for the plain design: [AlgorithmAndDatastructures-Plain-Builds](https://github.com/TobiasFaller/AlgorithmAndDatastructures-Plain-Builds)

**Pull request merged**
